import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// Providers
import StoreProvider from '@/providers/store-provider';
import ThemeProvider from '@/providers/theme-provider';
import DirectionProvider from '@/providers/direction-provider';
// Styles
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={inter.className}>
        <DirectionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <StoreProvider>{children}</StoreProvider>
          </ThemeProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
