import type { Metadata } from 'next';
import localFont from 'next/font/local';
// Providers
import StoreProvider from '@/providers/store-provider';
import ThemeProvider from '@/providers/theme-provider';
import DirectionProvider from '@/providers/direction-provider';
// Styles
import './globals.css';

const appFont = localFont({ src: 'MorabbaVF.ttf' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={appFont.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DirectionProvider>
            <StoreProvider>{children}</StoreProvider>
          </DirectionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
